<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }

        .header {
            text-align: center;
            margin-bottom: 15px;
        }

        .header h1 {
            margin: 0;
            font-size: 20px;
        }

        .header p {
            margin: 5px 0 0;
            font-size: 12px;
            color: #666;
        }

        .summary {
            margin-bottom: 15px;
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
        }

        .summary-box {
            padding: 8px 12px;
            background: #f5f5f5;
            border-radius: 4px;
            font-size: 12px;
            white-space: nowrap;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            table-layout: fixed;
        }

        th,
        td {
            padding: 5px;
            border: 1px solid #ddd;
            text-align: left;
            word-wrap: break-word;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
            font-size: 11px;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .footer {
            margin-top: 20px;
            font-size: 10px;
            color: #666;
            text-align: center;
        }

        .highlight {
            background-color: #fff8e1;
        }

        .danger {
            background-color: #ffebee;
        }

        /* Column width adjustments */
        .col-no {
            width: 3%;
        }

        .col-book {
            width: 18%;
        }

        .col-user {
            width: 15%;
        }

        .col-date {
            width: 8%;
        }

        .col-days {
            width: 7%;
        }

        .col-fine {
            width: 10%;
        }

        .col-status {
            width: 8%;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>
            Generated on: {{ $generatedAt }}
            @if ($fromDate || $toDate)
                | Date range: {{ $fromDate ?? 'Start' }} to {{ $toDate ?? 'End' }}
            @endif
        </p>
    </div>

    <div class="summary">
        <div class="summary-box">Total Overdue: {{ $totalOverdue }}</div>
        <div class="summary-box">Total Fine: Rs.{{ number_format($totalFine, 2) }}</div>
        <div class="summary-box">Fine Rate: Rs.{{ $policy->fine_per_day ?? 50 }}/day</div>
    </div>

    <table>
        <thead>
            <tr>
                <th class="col-no">#</th>
                <th class="col-book">Book</th>
                <th class="col-user">User</th>
                <th class="col-date">Issued Date</th>
                <th class="col-date">Due Date</th>
                <th class="col-date">Returned Date</th>
                <th class="col-days text-center">Days Overdue</th>
                <th class="col-fine text-right">Calculated Fine</th>
                <th class="col-status">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($overdueBooks as $index => $book)
                <tr
                    class="{{ $book['days_overdue'] > 30 ? 'danger' : ($book['days_overdue'] > 14 ? 'highlight' : '') }}">
                    <td class="col-no">{{ $index + 1 }}</td>
                    <td class="col-book">
                        <strong>{{ $book['book_name'] }}</strong><br>
                        <small>ISBN: {{ $book['book_isbn'] }}<br>{{ $book['book_author'] }}</small>
                    </td>
                    <td class="col-user">
                        <strong>{{ $book['user_name'] }}</strong><br>
                        <small>{{ $book['user_email'] }}</small>
                    </td>
                    <td class="col-date">{{ $book['issued_date'] }}</td>
                    <td class="col-date">{{ $book['due_date'] }}</td>
                    <td class="col-date">{{ $book['returned_date'] ?? '-' }}</td>
                    <td class="col-days text-center">{{ $book['days_overdue'] }}</td>
                    <td class="col-fine text-right">Rs.{{ number_format($book['calculated_fine'], 2) }}</td>
                    <td class="col-status">{{ ucfirst($book['status']) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="7" class="text-right">Totals:</th>
                <th class="text-right">Rs.{{ number_format($totalFine, 2) }}</th>
                <th></th>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>Generated by {{ config('app.name') }}</p>
    </div>

    <script type="text/php">
        if (isset($pdf)) {
            $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
            $size = 9;
            $font = $fontMetrics->getFont("Arial");
            $width = $fontMetrics->get_text_width($text, $font, $size) / 2;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 20;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>
</body>

</html>
