<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
        }

        .header p {
            margin: 5px 0 0;
            font-size: 14px;
            color: #666;
        }

        .summary {
            margin-bottom: 20px;
        }

        .summary-box {
            display: inline-block;
            padding: 10px 15px;
            margin-right: 10px;
            background: #f5f5f5;
            border-radius: 4px;
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            padding: 8px 12px;
            border: 1px solid #ddd;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .footer {
            margin-top: 30px;
            font-size: 12px;
            color: #666;
            text-align: center;
        }

        .highlight {
            background-color: #fff8e1;
        }

        .danger {
            background-color: #ffebee;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>
            Generated on: {{ $generatedAt }}
            @if ($fromDate || $toDate)
                | Date range: {{ $fromDate ?? 'Start' }} to {{ $toDate ?? 'End' }}
            @endif
        </p>
    </div>

    <div class="summary">
        <div class="summary-box">Total Overdue: {{ $totalOverdue }}</div>
        <div class="summary-box">Total Fine: Rs.{{ number_format($totalFine, 2) }}</div>
        <div class="summary-box">Total Paid: Rs.{{ number_format($totalPaid, 2) }}</div>
        <div class="summary-box">Remaining: Rs.{{ number_format($totalRemaining, 2) }}</div>
        <div class="summary-box">Fine Rate: Rs.{{ $policy->fine_per_day ?? 50 }}/day</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Book</th>
                <th>User</th>
                <th>Issued Date</th>
                <th>Due Date</th>
                <th>Days Overdue</th>
                <th class="text-right">Calculated Fine</th>
                <th class="text-right">Paid Amount</th>
                <th class="text-right">Remaining</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($overdueBooks as $index => $book)
                <tr
                    class="{{ $book['days_overdue'] > 30 ? 'danger' : ($book['days_overdue'] > 14 ? 'highlight' : '') }}">
                    <td>{{ $index + 1 }}</td>
                    <td>
                        {{ $book['book_name'] }}<br>
                        <small>ISBN: {{ $book['book_isbn'] }} | {{ $book['book_author'] }}</small>
                    </td>
                    <td>
                        {{ $book['user_name'] }}<br>
                        <small>{{ $book['user_email'] }}</small>
                    </td>
                    <td>{{ $book['issued_date'] }}</td>
                    <td>{{ $book['due_date'] }}</td>
                    <td class="text-center">{{ $book['days_overdue'] }}</td>
                    <td class="text-right">Rs.{{ number_format($book['calculated_fine'], 2) }}</td>
                    <td class="text-right">Rs.{{ number_format($book['paid_amount'], 2) }}</td>
                    <td class="text-right">Rs.{{ number_format($book['remaining_fine'], 2) }}</td>
                    <td>{{ ucfirst($book['status']) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="6" class="text-right">Totals:</th>
                <th class="text-right">Rs.{{ number_format($totalFine, 2) }}</th>
                <th class="text-right">Rs.{{ number_format($totalPaid, 2) }}</th>
                <th class="text-right">Rs.{{ number_format($totalRemaining, 2) }}</th>
                <th></th>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} | Page <span class="pageNumber"></span> of <span
                class="totalPages"></span></p>
    </div>

    <script type="text/php">
        if (isset($pdf)) {
            $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
            $size = 10;
            $font = $fontMetrics->getFont("Arial");
            $width = $fontMetrics->get_text_width($text, $font, $size) / 2;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 35;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>
</body>

</html>
